### ISSUE TITLE
Module needs to be fixed

### ISSUE THREAD

**Issue by bmsimons** [bmsimons/ps-spotify#5]
Spotify has made some API changes that render this PowerShell module unusable right now.

**Comment by thatguyfig** [comment]
Yeah I have noticed this also. I believe it may be due to Spotify changing the ports of the WebHelper.

Running 'Get-SpotifyWebHelperPort' returns the following error:


```
Get-NetTCPConnection : No matching MSFT_NetTCPConnection objects found by CIM query for 
instances of the ROOT/StandardCimv2/MSFT_NetTCPConnection class on the  CIM server: SELECT * 
FROM MSFT_NetTCPConnection  WHERE ((LocalPort = 4370) OR (LocalPort = 4371) OR (LocalPort = 
4372) OR (LocalPort = 4373) OR (LocalPort = 4374) OR (LocalPort = 4375) OR (LocalPort = 4376) 
OR (LocalPort = 4377) OR (LocalPort = 4378) OR (LocalPort = 4379) OR (LocalPort = 4380)) AND 
((OwningProcess = 4208) OR (OwningProcess = 8116) OR (OwningProcess = 13576) OR 
(OwningProcess = 16060)). Verify query parameters and retry.
At C:\Users\thorn\Documents\WindowsPowerShell\Modules\ps-spotify\ps-spotify-master\ps-spotify\
Private\Get-SpotifyWebHelperPort.ps1:32 char:32
+ ... nputObject (Get-NetTCPConnection -OwningProcess (Get-Process -Name "S ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (MSFT_NetTCPConnection:String) [Get-NetTCPConne 
   ction], CimJobException
    + FullyQualifiedErrorId : CmdletizationQuery_NotFound,Get-NetTCPConnection

```

I am going to see if I can track the related port down and get my version working.

**Comment by thatguyfig** [comment]
I found Spotify running on 4381, just outside the expected range for the module. I tried modifying my module to account for this but still doesn't appear to work.

Regardless of this, if you want this to resume working. I would suggest following the steps written by RiotKitten on the link below to downgrade your spotify version.

https://community.spotify.com/t5/Desktop-Linux-Windows-Web-Player/Where-can-I-download-the-previous-version/td-p/1039710/page/2

Old Spotify releases can be found here:
https://spotify.en.uptodown.com/windows/old

I used vers. 1.0.50.41368. but I am not sure if there later versions with it still working. Check Spotify go to settings in the arrow at the top right and scroll to the bottom where it says 'About Spotify' to see the version running.

Can confirm have restored functionality with the above steps.

**Comment by robinmalik** [comment]
Modifying `Get-SpotifyTrackStatus.ps1` and `Get-SpotifyCsrfKey.ps1` from https to https fixes this. Likely a change in Windows 10 that has stopped this from working. Alternatively there's some code floating around to trust insecure https connections, iirc.

**Comment by robinmalik** [comment]
Removed my original comment. Trying again:

Modifying Get-SpotifyTrackStatus.ps1 and Get-SpotifyCsrfKey.ps1 from https to http fixes this (port 4381 also, so the ranges in the functions need correcting). Likely a change in Windows that has stopped this from working - I know other code that's broken due to changes in SSL/TLS .NET settings by Microsoft. Alternatively there's some code floating around to trust insecure https connections, iirc.

Note: The returned object as a track property, which may appear empty in the console but if you inspect it, it's not 👍 

```
PS C:\> $t = Get-SpotifyTrackStatus
PS C:\> $t.track

track_resource  : @{name=Bob Ross Goes to Hollywood; uri=spotify:track:4vYcORoPBqumJgue4Zlivj; location=}
artist_resource : @{name=Birocratic; uri=spotify:artist:60b7IDlGflg5lgyfEGf9yB; location=}
album_resource  : @{name=Beets 4; uri=spotify:album:0BYFg5LjHvQZomF666Kaa2; location=}
length          : 189
track_type      : normal```

**Comment by bmsimons** [comment]
@robinmalik good to your that you got it working again 👍, in the meantime I have developed a .NET core web API application to fetch all needed authentication tokens to connect to Spotify through their public API. It's already available on GitHub at https://github.com/bmsimons/dotnet-core-spotify-authentication.

Spotify has added some features since the last commit, one of them is Spotify Connect. This completely eliminates the need to play around with ports and most importantly: the local Spotify 'helper' server.

I already have a development version available of some new cmdlets that allow controlling Spotify through PowerShell.

One of the pros of using Spotify Connect is that you can control all connected devices on your Spotify account: your smartphone, TV, computer, fancy new Sonos speaker, et cetera. This brings a lot more possibilities :)

I hope to get a public version out ASAP. Information about the Spotify Connect API can be found [here](https://developer.spotify.com/web-api/web-api-connect-endpoint-reference/).
